apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXhPVEV3TkRNek1Gb1hEVE16TURZeE5qRXdORE16TUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEJXCi9seXN1RDdrb0M3ejZ4eldoMi9ubHFza3VqV200QjRtU2NZQjNROXpUNWNmL2dYRUx4ZUZRTGpSdElhOTA3TGoKVWg0TnpEdnhsN1FVcGRQMjNwUFd6RkpKaVdnbzM1RVNUQkVEVUNoeERldFZzU3ZOSU5FaFl6MDNmNERHaGtUTwpHZG1ITE5xZTRJeVVIaFhYNTBjMjUvQTloTkFGa2QzZldURGc5TWtGVHVvT3EzTUc3OFRMMjJjOWM3d3RndXlmCjRvaTErT3JqTFJpSjdWbktHYStWOWZ5bHBEOEtNbUZzcEpzbHdPNVc3dEZlZ1VnQlZxNE8vellTNEY0czFmSUIKQTdsUFh1VC9xYU5CUXRtWitZeDFnVGNNYUIyai9PSWdDSWw0OVJBNFZaQlFCVy9XL3U4RlVMN3U3MUJFTlBsTApHVEpNT1RNS1U5dHNGdW5HVXpzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJb3hVWTF5M3E4N3VWanRCT1dyQXdVL0lqNXRNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS2d0ZXZBUVlIWkN5TW9JMDhFNgo0WmYwL2x3WXoxWGRHUmpQN1JKWU1jcG9LRVg2QUtjdFp0allVOFZKT0RzV2YvOWZIRXdtcXl0RUZ4d2d6RUg0CnNCdWQwOHB0QWI0KzNxdEJ6Tm0xZ0I2MHVuaUF1THljSmtEelUrb0VXSlRLOEpMYThiOGlEVFpqTHR3eExqVU4KOHRadFJpZ2l6QUltTXM0M1VOK0JyNlU2aiszYXp4THQyMW9GZlAvOEVBaFVuSm5PTkJmOHRkcHVSY1ptM1ErUgpMNFh2WE9YWDkrZGJaRXprT2ZmbEVPTCsxb2tyZ2xLamhzM1RIRW5KQndWNHFLckFyeVZSMDZDcTNBK0srazloCkZoWG54dzFLeVR4cHpjM2hZY2JuQjJydGlLblFZSDM0QS9NTFo1MUFidzZEaEVXZ2p5VlZ6N1lkWFRtaVVjUTgKNzBBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://688F650A507FB662A7150C5B015954C0.gr7.us-west-2.eks.amazonaws.com
  name: demo.us-west-2.eksctl.io
contexts:
- context:
    cluster: demo-eks.us-west-2.eksctl.io
    user: iam-root-account@demo-eks.us-west-2.eksctl.io
  name: iam-root-account@demo-eks.us-west-2.eksctl.io
- context:
    cluster: demo.us-west-2.eksctl.io
    user: iam-root-account@demo.us-west-2.eksctl.io
  name: iam-root-account@demo.us-west-2.eksctl.io
current-context: iam-root-account@demo.us-west-2.eksctl.io
kind: Config
preferences: {}
users:
- name: iam-root-account@demo.us-west-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - demo
      - --region
      - us-west-2
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
