name: spring boot
on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test
      run: mvn clean package -DskipTests=true 
    
    - name: push into ECR
      uses: vitr/actions-build-and-upload-to-ecs@master
      with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: demoapplication
          region: us-west-2
          tags: latest,${{ github.sha }}
          create_repo: true
    - name: Deploy to AWS EKS
      uses: giovannirossini/aws-eks-kubectl-action@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          cluster-name: 'demo'
          command: |
            kubectl  get nodes
  
