name: spring boot
on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test
      run: mvn clean package -DskipTests=true 
    
    - name: push into ECR
      uses: vitr/actions-build-and-upload-to-ecs@master
      with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: demoapplication
          region: ap-northeast-2
          tags: latest,${{ github.sha }}
          create_repo: true
    - name: update kube config
      run: aws eks update-kubeconfig --name demo-cluster --region us-west-2
    - name: Deploy to Eks 
      run: |
         kubectl apply -f demo-postgres-configmap.yml
         kubectl apply -f demo-postgres-credentials.yml
         kubectl apply -f demo-postgres-deployment.yml
         
          
         
